# Generated by Django 2.2 on 2021-03-17 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_auto_20210317_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
